font:
  normal:
    family: Hack
  size: 16.0

window:
  title: patrick-terminal

colors:
  primary:
    background: '0x0F111A'
    foreground: '0xD8DEE9'
  selection:
    background: '0x546E7A'
  cursor:
    text: CellBackground
    cursor: CellForeground
  normal:
    black:   '0x0F111A'
    red:     '0xF07178'
    green:   '0xC3E88D'
    yellow:  '0xFFCB6B'
    blue:    '0x82AAFF'
    magenta: '0xC792EA'
    cyan:    '0x89DDFF'
    white:   '0xEEFFFF'
  bright:
    black:   '0x546E7A'
    red:     '0xF07178'
    green:   '0xC3E88D'
    yellow:  '0xFFCB6B'
    blue:    '0x82AAFF'
    magenta: '0xC792EA'
    cyan:    '0x89DDFF'
    white:   '0xFFFFFF'
